language: node_js
sudo: false
node_js:
  - 7

cache:
  directories:
    - node_modules

install:
  - npm install
  - npm install coveralls

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run coveralls

before_deploy:
  - npm run release
