language: node_js
sudo: false
node_js:
- '7'
cache:
  directories:
  - "./node_modules"
env:
- UNITEST=1
matrix:
  include:
  - node_js: '7'
    env: COVERAGE=1
  - node_js: '7'
    env: SAUCE_LABS=1
  allow_failures:
  - node_js: '7'
    env: SAUCE_LABS=1
  global:
    secure: gEIla1ohzC3FMcpFrBURQrnFzr9oo3Bl5+JdbS/aAwu7ppP/l6+vEawNahChgTzRMzpgm7Akj5847gWVMTsKMVzYgAndK9ZSO8stDOu3rgEfuSJcVWDxI97NRAuGk1bPxXiOrjZLkhizMfvc9C5dbyEXEohePAiiMW4AgZ78XVESR4F8DZ0gCXn37XlD6bSK9/0PfdErvPhnRkOLPNIlgasUWfQkrZEnrmwRyQBqe1ttTzFJSVnt1zlPaYNcmFA5yRSqjYc5jEGCh2QWWq7QkEtGLSMNvvMrNCy6GDKBfvGEY0KmOu3GvFDgjYia18Pda8hlNdt8v9IoBV4UnAJxKV6rZ/yHksvQ2K8XygS5KAV3dj/TvuZS2a0i22V3SBR5dEcIQ+LKoS4/AucpX0NspgNBR/OAfk6GXPcl9BY/s2X7eC4aGsjWYnoNotKggJOVOEbN/q9TCW6Enq4uDhWVBf5z2YuHUr8u7qyW4sA8S9j0nVm1Opnt+9WNpnbtG73Gl9yYDC/arifiMuj8TteZO4gZvzlqscfwzz9F3AOtnAKwSe3erMnX9QeYU1bn0rf7iTxrzRkdoIwBgXEcRCpAphDzl9j0fJxXFPyehhOUEM2nN2l/Xa3Ib032nCcvk2ELUyCgxot/NqqIkaFYHF/FFk5iNGh1cS+AMCXGWJwQaSI=
addons:
  sauce_connect:
    username: DavidKk
  jwt:
    secure: o3kqfupTPNeuKDWRcLKoGvOyKhB7A7bhE2o15IOIhYddqFRrb9ngHAhR7I9LWQIKZGjIGQPwchTVSBRNvdRkQGK5QMOjunW7fp4DjrU/rt95Z7teZTc6O67Ic+lkznaxfZOXaAZ+0cCDrY6Hypcqwy9fVYyYvob1hJXv1fKui9aflFPwj4aY2gglzTL5KVnQeOiA68WDP2V0S7FBCAH56Kn/qwV6KzG0tjv6uJvfmeBTdw7Yt7ouf27BIuFc44oRKRZtRwqyLkTuK1AeWcYzXsCY44VZHQwFhk2AcgbVR1/wFJDme+7U+71xSOz1vtfEM/8iv7hfGUUnTN+wn3DIYkI2VC8iju86aYdyhttqiJuHsskZZehyiP2b+bmKCTQzR0zmpgR+TnowDPV0zRmhjR3kpuyvqLFiKU8MfcD0AUlO63voMZvE0/rl+ZNzlBPknbpqa3Wn+mPN3LRnISHmx8r/fv3cfSH0qtp11I+4CQm+5pZvQFyhFR7XCCS8rHrhtoJBxQ87tL3lLaI5Ow+VRRpbFs+jeLWPwuAMo5tUmiy5qFBIzqKF4OLG+SxSQvcDq3YodO2Q1gLRemUaOuScdcZlKlCgU5HtKjR+rabjqZnCM4SNFkKCpD+32U7RUsc60kB66KTCZm9EVSGFIZZ+yXbrO8YRKeez7qw8/CVHkgU=
install:
- npm install
- if [ "$COVERAGE" = 1 ]; then npm install codecov; fi
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- if [ "$COVERAGE" = 1 ]; then npm run codecov; fi
- if [ "$SAUCE_LABS" = 1 ]; then npm run unitest; fi
before_deploy:
- npm run build
- npm run document
deploy:
- provider: pages
  local_dir: docs
  skip_cleanup: true
  github_token:
    secure: dbL+LVT3jz6z0+x7mhNpj8f9WLYdEqc/jCULX+GhUGEUVVX5TrI1JLoxBlwGnzXmYb5cRqo8IC/eoHNHjSeV5g6Ay1nhsRHposeKfK5svAs7KzKHQCFxIZitCgvTiTVWSBtkdB8kVK5gSwTIq9FDeNnsTptBbEcnVVWEcFAbh/ndaZsfmMhfFHKgShKmy8ppxEr7VsvrQQXSX98zItZrxHGnrIBnHKpnFdff0FH8kTwyeJ3Ebq8zgtbCNhrzcNBsHk9F/qiyZrtCHsNOqDLFbT6dh29vRVLgeqxIbHnhpPv+x4WyHbKYs52pQCrR3+AUh87xjRvKtMIaBL9XrXSrU2coP6WvEroZf/3TBwouFGXIaKIoX0Wp76tI6wD3W0rkXtjw8ix8KKszWAbR7xbMHAhj5plr48lU1Vp9iwIEnTLXoZb9ujBQ4aN3T7noPtI4QDbJfj9sj4xBcXaC/UOmy5VkH2Fxn9Htp1B8fP75Ra4FxZCCdOhZ8oZRD4ZEznQbTPOw3NjY6V0y2RIxAfpK3otQwFmepDTam6FdaOGeMFXrw5TT4vHJCf0JyZ6TlIEySdwJqagTZHj7sKN6VQdBS9fCTewzwi12bfH5lJm4EsabKnNRgYTaw9dXIaL/5dKxiqQ+KH94DHat/cLguAWDLWMxYwHyX8GfzXmVOHzBy7k=
  on:
    branch: master
- provider: npm
  skip_cleanup: true
  email: qowera@qq.com
  api_key:
    secure: jZtSdAzjZTpnxRcSxhnnZB4VM49QYuEejKJnD0EiyH4EwvdKtFh4VDCBZ0Umjrt8ximx4GaE+HHApqZ1zwrVFXzc6FXW+5hmShJb0yAmRPQBFItLRuttZbaCfSRb+NyJFu3IiMw4VBkxaLXdLIwc9Ok1pedHdHZ5882PaYS3eh+MDd4pDqiSvCsZ7jrBKku9oxFDDwEdaV+JBHSnsajsThOBmlwHSHl81TF1mqKGkR32wCrRw9xzmKp0iYc9w4Kbz3nUqMVkPeVp3kTK22BpYK+cts2fJADSLDVZwv/l2o1NecMlyBs6+LXBAyqf7B8iLKtg0FR/b9mtinRGFwH8OEGtPGPR/eatrEGTgKcskCPbYIj53aYwoDifbWyaRF4Sv2SztE0hJ1+cGptkd7za1NGZbR1ymPrl0qQoTHS0Psn42oV+nErO2CeN4v+19iSZnHyRLVXm1XZMQw+cx8Iy2TzNedl6a6ZRKm3ZqrtO8jJS2jpj/GhMVQA/jrf/gKmPBITvSrEwf98qxZaJIS4kNZ025xm49aL8VQXTiEBF2pfw+8ct2Hw8ofeSeQ+i7iKgdXoS/+xUsFY4/taOg1pW18B5hDsUqjYn9irxuJGaPd5/oJnWaPOQnC0HMwGEt15K7g1vOdXgiaMsGx3ekHeShD3+P7XYh34xeml+c6/Rbj8=
  on:
    tags: true
