window.esdocSearchIndex = [
  [
    "qiniup/src/config.js~base64_regexp",
    "variable/index.html#static-variable-BASE64_REGEXP",
    "<span>BASE64_REGEXP</span> <span class=\"search-result-import-path\">qiniup/src/config.js</span>",
    "variable"
  ],
  [
    "qiniup/src/enum.js~enum",
    "class/src/enum.js~Enum.html",
    "<span>Enum</span> <span class=\"search-result-import-path\">qiniup/src/enum.js</span>",
    "class"
  ],
  [
    "qiniup/src/file.js~file",
    "class/src/file.js~File.html",
    "<span>File</span> <span class=\"search-result-import-path\">qiniup/src/file.js</span>",
    "class"
  ],
  [
    "qiniup/src/config.js~g",
    "variable/index.html#static-variable-G",
    "<span>G</span> <span class=\"search-result-import-path\">qiniup/src/config.js</span>",
    "variable"
  ],
  [
    "qiniup/src/config.js~k",
    "variable/index.html#static-variable-K",
    "<span>K</span> <span class=\"search-result-import-path\">qiniup/src/config.js</span>",
    "variable"
  ],
  [
    "qiniup/src/config.js~m",
    "variable/index.html#static-variable-M",
    "<span>M</span> <span class=\"search-result-import-path\">qiniup/src/config.js</span>",
    "variable"
  ],
  [
    "qiniup/src/config.js~qiniu_upload_https_url",
    "variable/index.html#static-variable-QINIU_UPLOAD_HTTPS_URL",
    "<span>QINIU_UPLOAD_HTTPS_URL</span> <span class=\"search-result-import-path\">qiniup/src/config.js</span>",
    "variable"
  ],
  [
    "qiniup/src/config.js~qiniu_upload_http_url",
    "variable/index.html#static-variable-QINIU_UPLOAD_HTTP_URL",
    "<span>QINIU_UPLOAD_HTTP_URL</span> <span class=\"search-result-import-path\">qiniup/src/config.js</span>",
    "variable"
  ],
  [
    "qiniup/src/event.js~qiniupevent",
    "class/src/event.js~QiniupEvent.html",
    "<span>QiniupEvent</span> <span class=\"search-result-import-path\">qiniup/src/event.js</span>",
    "class"
  ],
  [
    "qiniup/src/config.js~remote_file_url_regexp",
    "variable/index.html#static-variable-REMOTE_FILE_URL_REGEXP",
    "<span>REMOTE_FILE_URL_REGEXP</span> <span class=\"search-result-import-path\">qiniup/src/config.js</span>",
    "variable"
  ],
  [
    "qiniup/src/config.js~storage_prefix",
    "variable/index.html#static-variable-STORAGE_PREFIX",
    "<span>STORAGE_PREFIX</span> <span class=\"search-result-import-path\">qiniup/src/config.js</span>",
    "variable"
  ],
  [
    "qiniup/src/config.js~supported",
    "variable/index.html#static-variable-SUPPORTED",
    "<span>SUPPORTED</span> <span class=\"search-result-import-path\">qiniup/src/config.js</span>",
    "variable"
  ],
  [
    "qiniup/src/storage.js~storage",
    "class/src/storage.js~Storage.html",
    "<span>Storage</span> <span class=\"search-result-import-path\">qiniup/src/storage.js</span>",
    "class"
  ],
  [
    "qiniup/src/tunnel.js~tunnel",
    "class/src/tunnel.js~Tunnel.html",
    "<span>Tunnel</span> <span class=\"search-result-import-path\">qiniup/src/tunnel.js</span>",
    "class"
  ],
  [
    "qiniup/src/uploader.js~uploader",
    "class/src/uploader.js~Uploader.html",
    "<span>Uploader</span> <span class=\"search-result-import-path\">qiniup/src/uploader.js</span>",
    "class"
  ],
  [
    "qiniup/src/request.js~configure",
    "function/index.html#static-function-configure",
    "<span>configure</span> <span class=\"search-result-import-path\">qiniup/src/request.js</span>",
    "function"
  ],
  [
    "qiniup/src/utils.js~isnumeric",
    "function/index.html#static-function-isNumeric",
    "<span>isNumeric</span> <span class=\"search-result-import-path\">qiniup/src/utils.js</span>",
    "function"
  ],
  [
    "qiniup/src/request.js~post",
    "function/index.html#static-function-post",
    "<span>post</span> <span class=\"search-result-import-path\">qiniup/src/request.js</span>",
    "function"
  ],
  [
    "qiniup/src/request.js~request",
    "function/index.html#static-function-request",
    "<span>request</span> <span class=\"search-result-import-path\">qiniup/src/request.js</span>",
    "function"
  ],
  [
    "qiniup/src/utils.js~sizestringify",
    "function/index.html#static-function-sizeStringify",
    "<span>sizeStringify</span> <span class=\"search-result-import-path\">qiniup/src/utils.js</span>",
    "function"
  ],
  [
    "qiniup/src/request.js~upload",
    "function/index.html#static-function-upload",
    "<span>upload</span> <span class=\"search-result-import-path\">qiniup/src/request.js</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/config.js",
    "file/src/config.js.html",
    "src/config.js",
    "file"
  ],
  [
    "src/enum.js",
    "file/src/enum.js.html",
    "src/enum.js",
    "file"
  ],
  [
    "src/enum.js~enum#_inverted",
    "class/src/enum.js~Enum.html#instance-member-_inverted",
    "src/enum.js~Enum#_inverted",
    "member"
  ],
  [
    "src/enum.js~enum#_keys",
    "class/src/enum.js~Enum.html#instance-member-_keys",
    "src/enum.js~Enum#_keys",
    "member"
  ],
  [
    "src/enum.js~enum#_map",
    "class/src/enum.js~Enum.html#instance-member-_map",
    "src/enum.js~Enum#_map",
    "member"
  ],
  [
    "src/enum.js~enum#constructor",
    "class/src/enum.js~Enum.html#instance-constructor-constructor",
    "src/enum.js~Enum#constructor",
    "method"
  ],
  [
    "src/enum.js~enum#get",
    "class/src/enum.js~Enum.html#instance-method-get",
    "src/enum.js~Enum#get",
    "method"
  ],
  [
    "src/enum.js~enum#isvalidkey",
    "class/src/enum.js~Enum.html#instance-method-isValidKey",
    "src/enum.js~Enum#isValidKey",
    "method"
  ],
  [
    "src/enum.js~enum#value",
    "class/src/enum.js~Enum.html#instance-method-value",
    "src/enum.js~Enum#value",
    "method"
  ],
  [
    "src/event.js",
    "file/src/event.js.html",
    "src/event.js",
    "file"
  ],
  [
    "src/event.js~qiniupevent#constructor",
    "class/src/event.js~QiniupEvent.html#instance-constructor-constructor",
    "src/event.js~QiniupEvent#constructor",
    "method"
  ],
  [
    "src/file.js",
    "file/src/file.js.html",
    "src/file.js",
    "file"
  ],
  [
    "src/file.js~file#[key]",
    "class/src/file.js~File.html#instance-member-[key]",
    "src/file.js~File#[key]",
    "member"
  ],
  [
    "src/file.js~file#blob",
    "class/src/file.js~File.html#instance-member-blob",
    "src/file.js~File#blob",
    "member"
  ],
  [
    "src/file.js~file#cleancache",
    "class/src/file.js~File.html#instance-method-cleanCache",
    "src/file.js~File#cleanCache",
    "method"
  ],
  [
    "src/file.js~file#constructor",
    "class/src/file.js~File.html#instance-constructor-constructor",
    "src/file.js~File#constructor",
    "method"
  ],
  [
    "src/file.js~file#destory",
    "class/src/file.js~File.html#instance-method-destory",
    "src/file.js~File#destory",
    "method"
  ],
  [
    "src/file.js~file#export",
    "class/src/file.js~File.html#instance-method-export",
    "src/file.js~File#export",
    "method"
  ],
  [
    "src/file.js~file#file",
    "class/src/file.js~File.html#instance-member-file",
    "src/file.js~File#file",
    "member"
  ],
  [
    "src/file.js~file#getstate",
    "class/src/file.js~File.html#instance-method-getState",
    "src/file.js~File#getState",
    "method"
  ],
  [
    "src/file.js~file#hash",
    "class/src/file.js~File.html#instance-member-hash",
    "src/file.js~File#hash",
    "member"
  ],
  [
    "src/file.js~file#import",
    "class/src/file.js~File.html#instance-method-import",
    "src/file.js~File#import",
    "method"
  ],
  [
    "src/file.js~file#isuploaded",
    "class/src/file.js~File.html#instance-method-isUploaded",
    "src/file.js~File#isUploaded",
    "method"
  ],
  [
    "src/file.js~file#loadstate",
    "class/src/file.js~File.html#instance-method-loadState",
    "src/file.js~File#loadState",
    "method"
  ],
  [
    "src/file.js~file#savestate",
    "class/src/file.js~File.html#instance-method-saveState",
    "src/file.js~File#saveState",
    "method"
  ],
  [
    "src/file.js~file#setstate",
    "class/src/file.js~File.html#instance-method-setState",
    "src/file.js~File#setState",
    "method"
  ],
  [
    "src/file.js~file#settings",
    "class/src/file.js~File.html#instance-member-settings",
    "src/file.js~File#settings",
    "member"
  ],
  [
    "src/file.js~file#size",
    "class/src/file.js~File.html#instance-get-size",
    "src/file.js~File#size",
    "member"
  ],
  [
    "src/file.js~file#slice",
    "class/src/file.js~File.html#instance-method-slice",
    "src/file.js~File#slice",
    "method"
  ],
  [
    "src/file.js~file#state",
    "class/src/file.js~File.html#instance-member-state",
    "src/file.js~File#state",
    "member"
  ],
  [
    "src/file.js~file#storage",
    "class/src/file.js~File.html#instance-member-storage",
    "src/file.js~File#storage",
    "member"
  ],
  [
    "src/file.js~file#type",
    "class/src/file.js~File.html#instance-member-type",
    "src/file.js~File#type",
    "member"
  ],
  [
    "src/file.js~file.defaultsettings",
    "class/src/file.js~File.html#static-member-defaultSettings",
    "src/file.js~File.defaultSettings",
    "member"
  ],
  [
    "src/file.js~file.stateformatter",
    "class/src/file.js~File.html#static-member-stateFormatter",
    "src/file.js~File.stateFormatter",
    "member"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/request.js",
    "file/src/request.js.html",
    "src/request.js",
    "file"
  ],
  [
    "src/request.js~request",
    "typedef/index.html#static-typedef-Request",
    "src/request.js~Request",
    "typedef"
  ],
  [
    "src/storage.js",
    "file/src/storage.js.html",
    "src/storage.js",
    "file"
  ],
  [
    "src/storage.js~storage#constructor",
    "class/src/storage.js~Storage.html#instance-constructor-constructor",
    "src/storage.js~Storage#constructor",
    "method"
  ],
  [
    "src/storage.js~storage#del",
    "class/src/storage.js~Storage.html#instance-method-del",
    "src/storage.js~Storage#del",
    "method"
  ],
  [
    "src/storage.js~storage#get",
    "class/src/storage.js~Storage.html#instance-method-get",
    "src/storage.js~Storage#get",
    "method"
  ],
  [
    "src/storage.js~storage#set",
    "class/src/storage.js~Storage.html#instance-method-set",
    "src/storage.js~Storage#set",
    "method"
  ],
  [
    "src/storage.js~storage#settings",
    "class/src/storage.js~Storage.html#instance-member-settings",
    "src/storage.js~Storage#settings",
    "member"
  ],
  [
    "src/storage.js~storage.defaultsettings",
    "class/src/storage.js~Storage.html#static-member-defaultSettings",
    "src/storage.js~Storage.defaultSettings",
    "member"
  ],
  [
    "src/tunnel.js",
    "file/src/tunnel.js.html",
    "src/tunnel.js",
    "file"
  ],
  [
    "src/tunnel.js~tunnel#_exectokengetter",
    "class/src/tunnel.js~Tunnel.html#instance-method-_execTokenGetter",
    "src/tunnel.js~Tunnel#_execTokenGetter",
    "method"
  ],
  [
    "src/tunnel.js~tunnel#bput",
    "class/src/tunnel.js~Tunnel.html#instance-method-bput",
    "src/tunnel.js~Tunnel#bput",
    "method"
  ],
  [
    "src/tunnel.js~tunnel#constructor",
    "class/src/tunnel.js~Tunnel.html#instance-constructor-constructor",
    "src/tunnel.js~Tunnel#constructor",
    "method"
  ],
  [
    "src/tunnel.js~tunnel#fetch",
    "class/src/tunnel.js~Tunnel.html#instance-method-fetch",
    "src/tunnel.js~Tunnel#fetch",
    "method"
  ],
  [
    "src/tunnel.js~tunnel#mkblk",
    "class/src/tunnel.js~Tunnel.html#instance-method-mkblk",
    "src/tunnel.js~Tunnel#mkblk",
    "method"
  ],
  [
    "src/tunnel.js~tunnel#mkfile",
    "class/src/tunnel.js~Tunnel.html#instance-method-mkfile",
    "src/tunnel.js~Tunnel#mkfile",
    "method"
  ],
  [
    "src/tunnel.js~tunnel#request",
    "class/src/tunnel.js~Tunnel.html#instance-member-request",
    "src/tunnel.js~Tunnel#request",
    "member"
  ],
  [
    "src/tunnel.js~tunnel#resuming",
    "class/src/tunnel.js~Tunnel.html#instance-method-resuming",
    "src/tunnel.js~Tunnel#resuming",
    "method"
  ],
  [
    "src/tunnel.js~tunnel#settings",
    "class/src/tunnel.js~Tunnel.html#instance-member-settings",
    "src/tunnel.js~Tunnel#settings",
    "member"
  ],
  [
    "src/tunnel.js~tunnel#token",
    "class/src/tunnel.js~Tunnel.html#instance-member-token",
    "src/tunnel.js~Tunnel#token",
    "member"
  ],
  [
    "src/tunnel.js~tunnel#tokenexpire",
    "class/src/tunnel.js~Tunnel.html#instance-member-tokenExpire",
    "src/tunnel.js~Tunnel#tokenExpire",
    "member"
  ],
  [
    "src/tunnel.js~tunnel#upb64",
    "class/src/tunnel.js~Tunnel.html#instance-method-upb64",
    "src/tunnel.js~Tunnel#upb64",
    "method"
  ],
  [
    "src/tunnel.js~tunnel#upload",
    "class/src/tunnel.js~Tunnel.html#instance-method-upload",
    "src/tunnel.js~Tunnel#upload",
    "method"
  ],
  [
    "src/tunnel.js~tunnel.defaultsettings",
    "class/src/tunnel.js~Tunnel.html#static-member-defaultSettings",
    "src/tunnel.js~Tunnel.defaultSettings",
    "member"
  ],
  [
    "src/uploader.js",
    "file/src/uploader.js.html",
    "src/uploader.js",
    "file"
  ],
  [
    "src/uploader.js~uploader#constructor",
    "class/src/uploader.js~Uploader.html#instance-constructor-constructor",
    "src/uploader.js~Uploader#constructor",
    "method"
  ],
  [
    "src/uploader.js~uploader#fetch",
    "class/src/uploader.js~Uploader.html#instance-method-fetch",
    "src/uploader.js~Uploader#fetch",
    "method"
  ],
  [
    "src/uploader.js~uploader#settings",
    "class/src/uploader.js~Uploader.html#instance-member-settings",
    "src/uploader.js~Uploader#settings",
    "member"
  ],
  [
    "src/uploader.js~uploader#tunnel",
    "class/src/uploader.js~Uploader.html#instance-member-tunnel",
    "src/uploader.js~Uploader#tunnel",
    "member"
  ],
  [
    "src/uploader.js~uploader#upload",
    "class/src/uploader.js~Uploader.html#instance-method-upload",
    "src/uploader.js~Uploader#upload",
    "method"
  ],
  [
    "src/uploader.js~uploader.defaultsettings",
    "class/src/uploader.js~Uploader.html#static-member-defaultSettings",
    "src/uploader.js~Uploader.defaultSettings",
    "member"
  ],
  [
    "src/uploader.js~uploader.supported",
    "class/src/uploader.js~Uploader.html#static-member-supported",
    "src/uploader.js~Uploader.supported",
    "member"
  ],
  [
    "src/utils.js",
    "file/src/utils.js.html",
    "src/utils.js",
    "file"
  ]
]